    2: SceneGroup("Bass cover", [
            Scene("Toto - Rossana", play >> System(play_file("toto_rossana_no_bass.mp3"))),
            Scene("Toto - Africa", play >> System(play_file("toto_africa_no_bass.mp3"))),
            Scene("Yes - Owner of a lonely heart", play >> System(play_file("yes_owner_lonely_heart.mp3"))),
            Scene("Queen - I want to break free", play >> System(play_file("queen_want_break_free.mp3"))),
            Scene("Queen - Under Pressure", play >> System(play_file("queen_under_pressure.mp3"))),
            Scene("Queen - Crazy little thing called love", play >> System(play_file("queen_crazy_little_thing_called_love.mp3"))),
            Scene("Queen - Another one bites the dust", play >> System(play_file("queen_another_on_bites_dust.mp3"))),
            Scene("ZZ Top - Sharp dressed man", play >> System(play_file("zz_top_sharp_dressed_man.mp3"))),
            Scene("T4F - Head over heels", play >> System(play_file("t4f_head_over_heels.mp3"))),
            Scene("T4F - Head over heels - Synth", Transpose(-12) >> LatchNotes(False,reset='E2') >> lowsynth2),
            Scene("T4F - Everybody wants to rule the world", play >> System(play_file("t4f_everybody.mp3"))),
            Scene("Police - Walking on the moon", play >> System(play_file("police_walking_moon.mp3"))),
            Scene("Police - Message in a bottle", play >> System(play_file("police_message_bottle.mp3"))),
            Scene("Led Zeppelin - Rock and roll", play >> System(play_file("led_zeppelin_rock_and_roll.mp3"))),
            Scene("Bon Jovi - Livin on a prayer", play >> System(play_file("bon_jovi_prayer.mp3"))),
            Scene("Pat Metheny - Letter from home", play >> System(play_file("letter_from_home.mp3"))),
            Scene("Muse - Uprising", play >> System(play_file("uprising.mp3"))),
            Scene("Rush - The pass", play >> System(play_file("pass.mp3"))),
            Scene("Muse - Mission", play >> System(play_file("mission.mp3"))),
       ]),
