    2: SceneGroup("Timeline", [    
            Scene("Don't you forget about me", play >> System(play_file( "simplemind.mp3"))),
            Scene("ChinaGroove", play >> System(play_file( "china.mp3"))),
            Scene("Taking care of business", play >> System(play_file( "taking.mp3"))),
            Scene("Rolling in the Deep", play >> System(play_file( "rolling.mp3"))),
            Scene("Steve Miller Band - ROCK N ME", play >> System(play_file( "rock_n_me.mp3"))),
            Scene("Corbeau Illegal", play >> System(play_file( "illegal.mp3"))),
            Scene("Bryan Adams - Summer Of '69", play >> System(play_file( "summer.mp3"))),
            Scene("U2 - Pride (In The Name Of Love)", play >> System(play_file( "pride.mp3"))),
            Scene("Loverboy- Working For The Weekend", play >> System(play_file( "working_weekend.mp3"))),
            Scene("Doobie Brothers- Long train running", play >> System(play_file( "ltr.mp3"))),
            Scene("Toto - Hold The Line", play >> System(play_file( "hold_line.mp3"))),
            Scene("Foreigner-That_was_Yesterday", play >> System(play_file( "foreigner.mp3"))),
            Scene("Journey - Don't Stop Believin", play >> System(play_file( "journey_dsb.mp3"))),
            Scene("Journey - Seperate Ways", play >> System(play_file( "seperate.mp3"))),
            Scene("Sass Jordan_ So hard", play >> System(play_file( "so_hard.mp3"))),
       ]),   
