    2: SceneGroup("Timeline", [    
            Scene("Don't you forget about me", play >> System(player + "simplemind.mp3")),
            Scene("ChinaGroove", play >> System(player + "china.mp3")),
            Scene("Taking care of business", play >> System(player + "taking.mp3")),
            Scene("Rolling in the Deep", play >> System(player + "rolling.mp3")),
            Scene("Steve Miller Band - ROCK N ME", play >> System(player + "rock_n_me.mp3")),
            Scene("Corbeau Illegal", play >> System(player + "illegal.mp3")),
            Scene("Bryan Adams - Summer Of '69", play >> System(player + "summer.mp3")),
            Scene("U2 - Pride (In The Name Of Love)", play >> System(player + "pride.mp3")),
            Scene("Loverboy- Working For The Weekend", play >> System(player + "working_weekend.mp3")),
            Scene("Doobie Brothers- Long train running", play >> System(player + "ltr.mp3")),
            Scene("Toto - Hold The Line", play >> System(player + "hold_line.mp3")),
            Scene("Foreigner-That_was_Yesterday", play >> System(player + "foreigner.mp3")),
            Scene("Journey - Don't Stop Believin", play >> System(player + "journey_dsb.mp3")),
            Scene("Journey - Seperate Ways", play >> System(player + "seperate.mp3")),
            Scene("Sass Jordan_ So hard", play >> System(player + "so_hard.mp3")),
       ]),   
