    2: SceneGroup("Rush",
        [
            Scene("Subdivisions", init_patch=i_rush, patch=p_rush),
            Scene("The Trees", init_patch=i_rush_trees//Call(Playlist(playlist_config)), patch=p_rush_trees),
            Scene("Divers", init_patch=Call(Playlist(playlist_config)), patch=p_rush_trees),
            Scene("PowerWindows", init_patch=Call(Playlist(playlist_config)), patch=p_rush_trees),
            Scene("GraceUnderPressure", init_patch=Call(Playlist(playlist_config)), patch=p_rush_trees),
            Scene("Grand Designs", init_patch=i_rush_gd, patch=p_rush_gd),
            Scene("Marathon", init_patch=i_rush, patch=Discard()),
        ]),
    3: SceneGroup("BassCover",
        [
            Scene("Default", init_patch=Call(Playlist(playlist_config)), patch=U01_A),
            Scene("Queen", init_patch=Call(Playlist(playlist_config)), patch=U01_A),
            Scene("T4F", init_patch=Call(Playlist(playlist_config)), patch=U01_A),
            Scene("Toto", init_patch=Call(Playlist(playlist_config)), patch=U01_A),
        ]),
    4: SceneGroup("Futur",
        [
            Scene("Futur", init_patch=Discard(), patch=Discard()),
        ]),
    5: SceneGroup("Live",
        [
            Scene("In a big country", init_patch=i_big_country, patch=p_big_country),
        ]),
    6: SceneGroup("GrandDesignsStudio",
        [
            Scene("Default", init_patch=Discard(), patch=p_rush_gd),
        ]),
    7: SceneGroup("Demonstrations",
        [
            Scene("Default", init_patch=Discard(), patch=Discard()),
            Scene("BrushingSaw", LatchNotes(False, reset='f3') >> Transpose(-24) >> BrushingSaw),
            Scene("Explosion", patch=explosion),
            Scene("Demon", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Jokes", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Tabarnac", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("TLMEP", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
        ]),
    8: SceneGroup("Compositions",
        [
            Scene("Centurion", init_patch=i_centurion, patch=p_centurion),
        ]),
    9: SceneGroup("Musique",
        [
            Scene("Majestyx", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Delirium", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Hits", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Middleage", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("NinaHagen", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Palindrome", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("SteveMorse", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("Timeline", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
            Scene("TV", init_patch=Call(Playlist(playlist_config)), patch=Discard()),
        ]),
    10: SceneGroup("Éclairage HUE",
        [
            Scene("Init", init_patch=Discard(), patch=Discard()),
            Scene("Normal", init_patch=HueNormal, patch=Discard()),
            Scene("Galaxie", init_patch=HueGalaxie, patch=Discard()),
            Scene("Demon", init_patch=HueDemon, patch=Discard()),
            Scene("SoloRed", init_patch=HueSoloRed, patch=Discard()),
            Scene("Off", init_patch=HueOff, patch=Discard()),
        ]),


