    2: Scene("bass_cover", patch=Discard()),
    3: Scene("demon", patch=Discard()),
    4: Scene("styx", patch=Discard()),
    5: Scene("tabarnac", patch=Discard()),
    6: Scene("timeline", patch=Discard()),
    7: Scene("system", patch=Discard()),
    8: Scene("rush_cover", patch=Discard()),
